version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gobank
    ports: 
     - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/gobank?sslmode=disable
      - DB_DRIVER=postgres
      - SERVER_ADDRESS=0.0.0.0:8080
      - TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
      - ACCESS_TOKEN_DURATION=15m
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]